export { default as About } from "./about/About";
export { default as Avatar } from "./avatar/Avatar";
export { default as Certifications } from "./certifications/Certifications";
export { default as Greetings } from "./greetings/Greetings";
export { default as Header } from "./header/Header";
export { default as LanguageSelect } from "./language-select/LanguageSelect";
export { default as Skills } from "./skills/Skills";
export { default as SocialMedia } from "./social-media/SocialMedia";
export { default as Text } from "./text/Text";
