name: Build & Deploy - Portfolio

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  invoke_build:
    name: Build & Test
    uses: ./.github/workflows/reusable-node-build.yaml
  
  invoke_codeql:
    name: Scan
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: ./.github/workflows/reusable-codeql.yaml
  
  invoke_deploy:
    if: ${{ github.ref_name == 'main'}}
    name: Deploy
    needs: [invoke_build, invoke_codeql]
    permissions:
      pages: write
      contents: read
      id-token: write
    uses: ./.github/workflows/reusable-gh-pages-deploy.yaml
    with:
      environment: github-pages
      build_artifacts: ${{ needs.invoke_build.artifact_name }}
