name: Dependabot - Auto Approve & Merge

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ github.token }}
  PR_URL: ${{ github.event.pull_request.html_url }}

jobs:
  dependabot:
    if: ${{ github.actor == 'dependabot[bot]' }}
    name: Dependabot Automation
    runs-on: ubuntu-latest
    steps:
      - name: Approve pull request
        run: gh pr review --approve $PR_URL

      - name: Enable auto merge
        run: gh pr merge --auto --rebase $PR_URL
